services:
  - type: web
    name: backend
    env: node
    buildCommand: yarn install && yarn build:backend
    startCommand: yarn start:backend
    plan: free

  - type: web
    name: frontend
    env: static
    buildCommand: yarn install && yarn build:frontend
    staticPublishPath: frontend/dist
    plan: free